#!/usr/bin/env python2
"""
Copyright (C) 2017
    Jakub Krajniak (jkrajniak at gmail.com)

This file is part of AdResSLab.

AdResSLab is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

AdResSLab is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import espressopp  # NOQA
import numpy
from mpi4py import MPI
import random
import os
import time
from scipy.signal import savgol_filter

from adresslab import files_io, tools_adress
from adresslab import tools_sim as tools
from adresslab import gromacs_topology


from adresslab.app_args import _args_md as _args

# GROMACS units, kJ/mol K
kb = 0.0083144621

# Storage options

# Mostly you do not need to modify lines below.
def main():  # NOQA
    time0 = time.time()
    args = _args().parse_args()

    max_cutoff = args.cutoff

    print('Welcome in AdResSLab!')

    generate_exclusions = args.exclusion_list is None or not os.path.exists(args.exclusion_list)

    input_conf = gromacs_topology.read(args.top, doRegularExcl=generate_exclusions)
    input_gro_conf = files_io.GROFile(args.conf)
    input_gro_conf.read()

    if not generate_exclusions:
        exclusion_file = open(args.exclusion_list, 'r')
        exclusions = [map(int, x.split()) for x in exclusion_file.readlines()]
        print('Read exclusion list from {} (total: {})'.format(args.exclusion_list, len(exclusions)))
        input_conf = input_conf._replace(exclusions=exclusions)
    else:
        exclusion_list_file = 'exclusion_{}.list'.format(args.top.split('.')[0])
        with open(exclusion_list_file, 'w') as fel:
            for p in input_conf.exclusions:
                fel.write('{} {}\n'.format(*p))
        print('Save exclusion list: {} ({})'.format(exclusion_list_file, len(input_conf.exclusions)))

    box = input_gro_conf.box
    print('Setting up simulation...')

    # Tune simulation parameter according to arguments
    integrator_step = args.int_step
    k_steps = int(args.run / integrator_step)

    if args.skin:
        skin = args.skin
    else:
        skin = 0.16

    rng_seed = args.rng_seed
    if args.rng_seed == -1:
        rng_seed = random.randint(1, 10000)
        args.rng_seed = rng_seed

    # Initialize RNG
    random.seed(rng_seed)

    # Save the params to the the file.
    _args().save_to_file('{}_{}_params.out'.format(args.output_prefix, rng_seed), args)

    print('Skin: {}'.format(skin))
    print('RNG Seed: {}'.format(rng_seed))
    print('Time step: {}'.format(args.dt))
    print('Cutoff: {}'.format(max_cutoff))
    print('Boltzmann constant = {}'.format(kb))

    # Setup system
    system = espressopp.System()
    system.rng = espressopp.esutil.RNG(rng_seed)
    # Temperature in kb units
    temperature = args.temperature * kb

    # Generate particle lists.
    part_prop, all_particles, adress_tuple = tools.genParticleList(
        input_conf, input_gro_conf, adress=True, use_charge=True, temperature=temperature)
    print('Reads {} particles with properties {}'.format(len(all_particles), part_prop))

    if input_conf.charges:
        print('Total charge: {}'.format(sum(input_conf.charges)))

    print('Running with box {}'.format(box))
    system.bc = espressopp.bc.OrthorhombicBC(system.rng, box)
    system.skin = skin

    if args.node_grid:
        nodeGrid = map(int, args.node_grid.split(','))
    else:
        nodeGrid = espressopp.tools.decomp.nodeGrid(MPI.COMM_WORLD.size)
    print('Number of nodes {}, node-grid: {}'.format(
        MPI.COMM_WORLD.size, nodeGrid))
    if args.cell_grid:
        cellGrid = map(int, args.cell_grid.split(','))
    else:
        cellGrid = espressopp.tools.decomp.cellGrid(box, nodeGrid, max_cutoff, skin)
    print('Cell grid: {}'.format(cellGrid))

    system.storage = espressopp.storage.DomainDecompositionAdress(system, nodeGrid, cellGrid)

    integrator = espressopp.integrator.VelocityVerlet(system)
    integrator.dt = args.dt
    system.integrator = integrator

    # Adds particles here
    # Apparently AdResS required to first add CG particle and then the corresponding AT particles...
    tmpp = []
    new_plist = []
    for p in all_particles:
        if p.adrat == 1:  # atomistic particle
            tmpp.append(tuple(p))
        else:  # CG particle
            new_plist.append(tuple(p))
            new_plist.extend(tmpp)
            tmpp = []
    system.storage.addParticles(new_plist, *part_prop)

    print('Set {} AdResS tuples'.format(len(adress_tuple)))

    ftpl = espressopp.FixedTupleListAdress(system.storage)
    ftpl.addTuples(adress_tuple)
    system.storage.setFixedTuplesAdress(ftpl)

    system.storage.decompose()

    print('Prepared:')
    print('Bonds: {}'.format(sum(len(x) for x in input_conf.bondtypes.values())))
    print('Angles: {}'.format(sum(len(x) for x in input_conf.angletypes.values())))
    print('Dihedrals: {}'.format(sum(len(x) for x in input_conf.dihedraltypes.values())))
    print('Pairs: {}'.format(sum(len(x) for x in input_conf.pairtypes.values())))

    print('Setting AdResS module')
    print('Excplicit: {}'.format(args.adress_ex))
    print('Hybrid: {}'.format(args.adress_hy))
    if args.adress_centre == 'box_centre':
        adr_centre = [box[0]/2.0, box[1]/2.0, box[2]/2.0]
    else:
        adr_centre = map(float, args.adress_centre.split(','))

    if args.adress_use_sphere and args.calculate_tf:
        # TODO(jakub): Add support for spherical AdResS region in case of TD-force calculation.
        raise RuntimeError('Sphere AdResS region not supported for TD-force calculation')

    print('Centre coordinates: {}'.format(adr_centre))
    print('Spherical region: {}'.format(args.adress_use_sphere))

    # Define interactions.
    verletlist = espressopp.VerletListAdress(system, cutoff=max_cutoff, adrcut=max_cutoff,
                                             dEx=args.adress_ex, dHy=args.adress_hy,
                                             adrCenter=adr_centre,
                                             sphereAdr=args.adress_use_sphere)
    verletlist.exclude(input_conf.exclusions)

    lj_interaction = tools.setLennardJonesInteractions(
        input_conf, verletlist, max_cutoff, input_conf.nonbond_params, ftpl=ftpl)
    coulomb_interaction = gromacs_topology.setCoulombInteractions(system,
                                                                  verletlist,
                                                                  max_cutoff,
                                                                  input_conf.atomtypeparams,
                                                                  epsilon1=args.coulomb_epsilon1,
                                                                  epsilon2=args.coulomb_epsilon2,
                                                                  kappa=args.coulomb_kappa,
                                                                  ftpl=ftpl)

    tools.setTabulatedInteractions(input_conf.atomtypeparams, max_cutoff, lj_interaction)
    tools.setBondedInteractions(system, input_conf, ftpl)
    tools.setAngleInteractions(system, input_conf, ftpl)
    tools.setDihedralInteractions(system, input_conf, ftpl)

    system.addInteraction(lj_interaction, 'lj')
    system.addInteraction(coulomb_interaction, 'coulomb')

    print('Number of interactions: {}'.format(system.getNumberOfInteractions()))

    # Define the thermostat
    print('Temperature: {} ({}), gamma: {}'.format(args.temperature, temperature, args.thermostat_gamma))
    print('Thermostat: {}'.format(args.thermostat))
    if args.thermostat == 'lv':
        thermostat = espressopp.integrator.LangevinThermostat(system)
        thermostat.temperature = temperature
        thermostat.gamma = args.thermostat_gamma
        thermostat.adress = True
    elif args.thermostat == 'vr':
        raise RuntimeError('Stochastic velocity rescale does not support AdResS, use Langevin.')
        # thermostat = espressopp.integrator.StochasticVelocityRescaling(system)
        # thermostat.temperature = temperature
        # thermostat.coupling = args.thermostat_gamma
    integrator.addExtension(thermostat)

    print("Added tuples, decomposing now ...")

    ext_analysis, system_analysis = tools.setSystemAnalysis(
        system, integrator, args, args.energy_collect,
        particle_types=[t for t, d in input_conf.atomtypeparams.items() if d['particletype'] == 'A'])

    if args.remove_com > 0:
        print('Removes total velocity of the system every {} steps'.format(args.remove_com))
        total_velocity = espressopp.analysis.CMVelocity(system)
        ext_remove_com = espressopp.integrator.ExtAnalyze(total_velocity, args.remove_com)
        integrator.addExtension(ext_remove_com)

    print('Number of particles: {}'.format(len(all_particles)))

    # add AdResS
    adress = espressopp.integrator.Adress(system, verletlist, ftpl)
    integrator.addExtension(adress)

    # Thermodynamic force
    use_thforce = False
    single_thforce = False
    if args.tabletf:
        use_thforce = True
        print('Setting thermodynamic force: {}'.format(args.tabletf))
        tabletfs = args.tabletf.split(',')
        thdforce = espressopp.integrator.TDforce(system, verletlist)
        if len(tabletfs) > 1 and ':' not in args.tabletf:
            raise RuntimeError('Only single global thermodynamic force can be specify')
        if len(tabletfs) == 1:
            # Set TF force for CG types
            tools_adress.set_single_th_force(thdforce, input_conf, tabletfs[0])
            single_thforce = True
        else:
            type_name2type_id = {
                td.get('atnum', td.get('atname')): tid
                for tid, td in input_conf.atomtypeparams.items()}
            for tblfs in tabletfs:
                table_name, type_name = tblfs.split(':')
                if type_name not in type_name2type_id:
                    raise RuntimeError('Type name {} not found'.format(type_name))
                thdforce.addForce(itype=3, filename=table_name, type=type_name2type_id[type_name])
                print('Set TF force for type: {} table: {}'.format(type_name, table_name))

    if args.cap_force:
        print('Define maximum cap-force in the system (max: {})'.format(args.cap_force))
        cap_force = espressopp.integrator.CapForce(system, args.cap_force)
        integrator.addExtension(cap_force)

    print('Decomposing...')
    espressopp.tools.AdressDecomp(system, integrator)

    # Let's compute density along X-axis
    xdensity_dr = 0.05
    xdensity_bins = int(box[0]/xdensity_dr)
    compute_density_profile = args.compute_density_profile or args.calculate_tf
    # Only atomistic particles
    at_masses = [m for i, m in enumerate(input_conf.masses)
                 if input_conf.atomtypeparams[input_conf.types[i]]['particletype'] == 'A']
    average_density = sum(at_masses)/(box[0]*box[1]*box[2])
    print('Average density: {}'.format(average_density))
    if compute_density_profile:
        xdensity_comp = espressopp.analysis.XDensity(system)
        xdensity = numpy.array(xdensity_comp.compute(xdensity_bins))

    if args.calculate_tf and not single_thforce:
        # TODO(jakub): Generalized it.
        raise RuntimeError('Calculation of TD-force only for a single table.')

    if args.calculate_tf:
        x_r = numpy.arange(0, box[0], xdensity_dr)
        adr_centre_idx = int(adr_centre[0]/xdensity_dr)
        # Indexes with respect to adr_centre_idx (0)
        adr_ex_idx = int((args.adress_ex)/xdensity_dr)  # end of ex region
        adr_hy_idx = int((args.adress_ex + args.adress_hy) / xdensity_dr)  # end of hy region
        # Set zero TH force for step0
        tf_new = '{}_{}_th_s{}.xvg'.format(args.output_prefix, rng_seed, 0)
        zero_th = numpy.zeros((x_r[adr_centre_idx:].shape[0], 3))
        zero_th[:, 0] = x_r[:adr_centre_idx]
        numpy.savetxt(tf_new, zero_th)
        tools_adress.set_single_th_force(thdforce, input_conf, tf_new)
        last_th_force = zero_th[:, 2]

        for _s in range(1, args.tf_max_steps+1):
            # Main integrator loop.
            xdensity = numpy.array(xdensity_comp.compute(xdensity_bins))
            for k in range(k_steps):
                integrator.run(args.int_step)
                system_analysis.info()
                xdensity += numpy.array(xdensity_comp.compute(xdensity_bins))

            xdensity = xdensity / (k_steps + 1)
            xdensity *= average_density

            xdensity_file = '{}_{}_xdensity_s{}.csv'.format(args.output_prefix, rng_seed, _s)
            print('Saved x-density: {}'.format(xdensity_file))
            numpy.savetxt(xdensity_file, numpy.column_stack((x_r, xdensity)))

            # For TF we need only part of the density profile.
            rho = numpy.ones(xdensity[adr_centre_idx:].shape[0]) * average_density  # Only half from ADR centre
            rho[adr_ex_idx-1:adr_hy_idx+1] = xdensity[adr_centre_idx+adr_ex_idx-1:adr_centre_idx+adr_hy_idx+1]
            rho_s = savgol_filter(rho, 21, 5, mode='nearest')  # Make it smooth
            drho_s = savgol_filter(rho_s, 21, 5, deriv=1, mode='nearest')   # Get the force

            # Substract the force from the previouse step (with prefactor)
            new_th_force = last_th_force - args.tf_prefactor*drho_s

            # Save the new table
            tf_new = '{}_{}_th_s{}.xvg'.format(args.output_prefix, rng_seed, _s)
            numpy.savetxt(tf_new, numpy.column_stack((x_r[:adr_centre_idx], rho, new_th_force)))
            print('Saved new tf force to: {}'.format(tf_new))

            # Save force from current step as last step and set new TD force
            last_th_force = new_th_force
            tools_adress.set_single_th_force(thdforce, input_conf, tf_new)
    else:  # Standard simulation
        # Do not store trajectory when requested calculate TF.
        trj_filename = '{}_{}_traj_at'.format(args.output_prefix, rng_seed)
        dump_conf = None
        if args.output_format == 'gro':
            trj_filename = '{}.gro'.format(trj_filename)
            dump_conf = espressopp.io.DumpGROAdress(
                system,
                ftpl,
                integrator,
                filename='{}.gro'.format(trj_filename),
                unfolded=True)
        elif args.output_format == 'xtc':
            trj_filename = '{}.gro'.format(trj_filename)
            dump_conf = espressopp.io.DumpXTCAdress(
                system,
                ftpl,
                integrator,
                unfolded=True,
                append=True,
                filename='{}.xtc'.format(trj_filename))
        elif args.output_format:
            raise RuntimeError('Traj dump {} not supported'.format(args.output_format))

        if dump_conf:
            ext_dump = espressopp.integrator.ExtAnalyze(dump_conf, args.trj_collect)
            integrator.addExtension(ext_dump)
            print('Collect trajectory every {} in {}'.format(trj_filename, args.trj_collect))

        # Main integrator loop.
        for k in range(k_steps):
            integrator.run(args.int_step)
            system_analysis.info()
            if compute_density_profile:
                xdensity += numpy.array(xdensity_comp.compute(xdensity_bins))

        # Calculate average of the density profile.
        if compute_density_profile:
            xdensity = xdensity / (k_steps+1)
            xdensity = numpy.column_stack((numpy.arange(0, box[0], xdensity_dr), xdensity*average_density))

            xdensity_file = '{}_{}_xdensity.csv'.format(args.output_prefix, rng_seed)
            numpy.savetxt(xdensity_file, xdensity)
            print('Saved x-density: {}'.format(xdensity_file))

    print('Finished!')
    print('Total time: {}'.format(time.time() - time0))
    espressopp.tools.analyse.final_info(system, integrator, verletlist, time0, time.time())


if __name__ == '__main__':
    main()
